# Generated by Django 5.2.8 on 2025-11-13 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure', models.CharField(max_length=100, verbose_name='Departure location')),
                ('arrival', models.CharField(max_length=100, verbose_name='Arrival location')),
                ('off_block', models.TimeField(blank=True, null=True, verbose_name='Off block (departure time)')),
                ('on_block', models.TimeField(blank=True, null=True, verbose_name='On block (arrival time)')),
                ('uav_type', models.CharField(help_text='e.g. DJI Mavic 3, WingtraOne, etc.', max_length=100, verbose_name='UAV type (make/model/variant)')),
                ('uav_reg', models.CharField(help_text='Aircraft registration / ID', max_length=50, verbose_name='UAV registration')),
                ('gcs_type', models.CharField(blank=True, help_text='Ground control station make/model (optional)', max_length=100, verbose_name='GCS type')),
                ('gcs_reg', models.CharField(blank=True, max_length=50, verbose_name='GCS registration / ID')),
                ('engine_class', models.CharField(blank=True, help_text='Optional for UAS, e.g. SE/ME or empty.', max_length=10, verbose_name='Engine class (SE/ME)')),
                ('pilot_role', models.CharField(choices=[('PIC', 'Pilot in Command'), ('COP', 'Co-pilot'), ('OBS', 'Observer / VO'), ('STU', 'Student / Trainee'), ('INS', 'Instructor'), ('EXM', 'Examiner'), ('OTH', 'Other')], default='PIC', help_text='Your function on this flight (PIC, observer, instructor, etc.)', max_length=3, verbose_name='Pilot role')),
                ('connection_time', models.TimeField(blank=True, help_text='Time when GCS connected to UAV', null=True, verbose_name='GCS connected')),
                ('engine_start', models.TimeField(blank=True, null=True, verbose_name='Engine start')),
                ('takeoff', models.TimeField(blank=True, null=True, verbose_name='Takeoff')),
                ('landing', models.TimeField(blank=True, null=True, verbose_name='Landing')),
                ('engine_stop', models.TimeField(blank=True, null=True, verbose_name='Engine stop')),
                ('disconnection_time', models.TimeField(blank=True, help_text='Time when GCS disconnected from UAV', null=True, verbose_name='GCS disconnected')),
                ('landings_day', models.PositiveIntegerField(default=0, verbose_name='Landings (day)')),
                ('landings_night', models.PositiveIntegerField(default=0, verbose_name='Landings (night)')),
                ('man_takeoff', models.PositiveIntegerField(default=0, verbose_name='Manual takeoffs')),
                ('man_landings', models.PositiveIntegerField(default=0, verbose_name='Manual landings')),
                ('a_to', models.PositiveIntegerField(default=0, verbose_name='Autonomous takeoffs')),
                ('a_l', models.PositiveIntegerField(default=0, verbose_name='Autonomous landings')),
                ('flight_time', models.PositiveIntegerField(blank=True, help_text='Landing - Takeoff (auto if both given)', null=True, verbose_name='Flight time (min)')),
                ('block_time', models.PositiveIntegerField(blank=True, help_text='On block - Off block (auto if both given)', null=True, verbose_name='Block time (min)')),
                ('engine_time', models.PositiveIntegerField(blank=True, help_text='Engine stop - Engine start (auto if both given)', null=True, verbose_name='Engine time (min)')),
                ('gcs_time', models.PositiveIntegerField(blank=True, help_text='GCS disconnect - GCS connect (auto if both given)', null=True, verbose_name='GCS time (min)')),
                ('is_simulator', models.BooleanField(default=False, help_text='Tick if this was an FSTD/simulator session rather than an actual flight.', verbose_name='Simulator session')),
                ('simulator_type', models.CharField(blank=True, max_length=100, verbose_name='Simulator type')),
                ('simulator_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Simulator time (min)')),
                ('remarks', models.TextField(blank=True, help_text='Skill tests, proficiency checks, incidents, etc.', verbose_name='Remarks / skill tests / checks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uas_flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
