# Generated by Django 5.2.8 on 2025-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightlogentry',
            old_name='landings_day',
            new_name='landing_day',
        ),
        migrations.RenameField(
            model_name='flightlogentry',
            old_name='landings_night',
            new_name='landing_night',
        ),
        migrations.RemoveField(
            model_name='flightlogentry',
            name='a_l',
        ),
        migrations.RemoveField(
            model_name='flightlogentry',
            name='a_to',
        ),
        migrations.RemoveField(
            model_name='flightlogentry',
            name='man_landings',
        ),
        migrations.RemoveField(
            model_name='flightlogentry',
            name='man_takeoff',
        ),
        migrations.AddField(
            model_name='flightlogentry',
            name='takeoff_day',
            field=models.PositiveIntegerField(default=0, verbose_name='Takeoffs (day)'),
        ),
        migrations.AddField(
            model_name='flightlogentry',
            name='takeoff_night',
            field=models.PositiveIntegerField(default=0, verbose_name='Takeoffs (night)'),
        ),
        migrations.AlterField(
            model_name='flightlogentry',
            name='block_time',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Block time (min)'),
        ),
        migrations.AlterField(
            model_name='flightlogentry',
            name='engine_time',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Engine time (min)'),
        ),
        migrations.AlterField(
            model_name='flightlogentry',
            name='flight_time',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Flight time (min)'),
        ),
        migrations.AlterField(
            model_name='flightlogentry',
            name='gcs_time',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='GCS time (min)'),
        ),
    ]
