# Generated by Django 5.2.8 on 2025-11-14 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_rename_landings_day_flightlogentry_landing_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Medical certificate (PDF)')),
                ('flight_crew_license', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Flight crew license (PDF)')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Other document')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
